name: bigbench-play
channels:
  - pytorch

# These are our environment dependencies, which are pinned to versions compatible
# with the libraries defined in pyproject.toml, which mostly matters for the like 
# of tensorflow and torch.
# Everything we can, we manage with poetry.
# [0] https://www.tensorflow.org/install/source#gpu
# [1] https://pytorch.org/get-started/locally/
dependencies:
  - python=3.8
  - poetry=1.1
  - cudatoolkit=11.3